export const faceTypes = ["All", "Cute", "Animals", "Wat", "Happy", "OMG"];

export const textfaces = [
  { face: "( ͡° ͜ʖ ͡°)", type: "Wat" },
  { face: "¯\\_(ツ)_/¯", type: "Wat" },
  { face: "ಠ_ಠ", type: "Wat" },
  { face: "ʕ•ᴥ•ʔ", type: "Cute" },
  { face: "༼ つ ◕_◕ ༽つ", type: "Cute" },
  { face: "ฅ^•ﻌ•^ฅ", type: "Animals" },
  { face: "V●ᴥ●V", type: "Animals" },
  { face: "/ᐠ｡ꞈ｡ᐟ\\", type: "Animals" },
  { face: "₍ᐢ. ̫.ᐢ₎", type: "Animals" },
  { face: "૮ ・ﻌ・ა", type: "Animals" },
  { face: "ʕっ•ᴥ•ʔっ", type: "Animals" },
  { face: "／(･ × ･)＼", type: "Animals" },
  { face: "Ꮚ˘ ꈊ ˘ Ꮚ", type: "Animals" },
  { face: "ʚ(｡˃ ᵕ ˂ )ɞ", type: "Animals" },
  { face: "くコ:彡", type: "Animals" },
  { face: "(╯°□°)╯︵ ┻━┻", type: "OMG" },
  { face: "┬─┬ ノ( ゜-゜ノ)", type: "OMG" },
  { face: "(ง'̀-'́)ง", type: "OMG" },
  { face: "(ಥ﹏ಥ)", type: "OMG" },
  { face: "(ﾉ◕ヮ◕)ﾉ*:･ﾟ✧", type: "Happy" },
  { face: "(☞ﾟヮﾟ)☞", type: "Happy" },
  { face: "(•_•) ( •_•)>⌐■-■ (⌐■_■)", type: "Wat" },
  { face: "┬┴┬┴┤ ͜ʖ ͡°) ├┬┴┬┴", type: "Wat" },
  { face: "ᕙ(⇀‸↼‶)ᕗ", type: "OMG" },
  { face: "♪~ ᕕ(ᐛ)ᕗ", type: "Happy" },
  { face: "(づ｡◕‿‿◕｡)づ", type: "Cute" },
  { face: "(¬_¬)", type: "Wat" },
  { face: "¯\\(°_o)/¯", type: "Wat" },
  { face: "༼ つ ͡° ͜ʖ ͡° ༽つ", type: "Wat" },
  { face: "(ノಠ益ಠ)ノ彡┻━┻", type: "OMG" },
  { face: "(◕‿◕✿)", type: "Cute" },
  { face: "ಠ⌣ಠ", type: "Happy" },
  { face: "(￣^￣)ゞ", type: "Happy" },
  { face: "(｡◕‿◕｡)", type: "Cute" },
];

export const faces = textfaces.map(({ face }) => face);
